my_blog/blog/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^', views.),
]

my_blog/my_blog/apps/blogs/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(),name='login'),
    url(r'^details/$', views.LoginsuccessView.as_view(),name='details'),
    url(r'^register/$', views.RegisterView.as_view(),name='register'),
    url(r'^det_index/$', views.Det_indexView.as_view(),name='det_index'),
    url(r'^whisper/$', views.WhisperView.as_view(),name='whisper'),
    url(r'^leacots/$', views.LeacotsView.as_view(),name='leacots'),
    url(r'^album/$', views.AlbumView.as_view(),name='album'),
    url(r'^about/$', views.AboutView.as_view(),name='about'),

]
#
# class ="layui-nav-item" > < a href="det_index.html" class ="active" > 文章 < / a > < / li >
# class ="layui-nav-item" > < a href="whisper.html" > 微语 < / a > < / li >
# class ="layui-nav-item" > < a href="leacots.html" > 留言 < / a > < / li >
# class ="layui-nav-item" > < a href="album.html" > 相册 < / a > < / li >
# class ="layui-nav-item" > < a href="about.html" class ="active" > 关于 < / a > < / li >

my_blog/my_blog/apps/index/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'index/$', views.IndexView.as_view(), name='index'),
]

my_blog/my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 首页
    url(r'^', include('index.urls', namespace='index')),
    # 功能页
    url(r'^', include('blogs.urls', namespace='blogs')),

]

my_blog/my_blog/apps/blogs/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib import admin
from django.urls import reverse
from django.utils.timezone import now


# Create your models here.

class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=200)
    nickname = models.CharField(max_length=50, default='匿名')
    email = models.EmailField()
    created_time = models.CharField(max_length=50, default=now)
    comment_num = models.PositiveIntegerField(verbose_name='评论数', default=0)
    avatar = models.ImageField(upload_to='media', default="media/default.png")

    def __str__(self):
        return self.username

    def comment(self):
        self.comment_num += 1
        self.save(update_fields=['comment_num'])

    def comment_del(self):
        self.comment_num -= 1
        self.save(update_fields=['comment_num'])


class UserAdmin(admin.ModelAdmin):
    list_display = ('username', 'email')


# class Article(models.Model):
#     # id =
class ArticleComment(models.Model):
    body = models.TextField()
    username = models.CharField(max_length=50)
    createtime = models.DateTimeField(verbose_name='创建时间', default=now)

    # 使对象在后台显示更友好
    def __str__(self):
        return self.article

my_blog/my_blog/apps/index/models.py
from django.db import models

# Create your models here.

my_blog/my_blog/apps/blogs/views.py
# Create your views here.
from django.shortcuts import render
from django.views import View
from .models import User, ArticleComment
from datetime import datetime


# 登录视图

class LoginView(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        user_name = request.POST.get('username', '')
        pass_word = request.POST.get('password', '')
        user = User.objects.filter(username=user_name)  # 查看数据库里是否有该用户名
        if user:  # 如果存在
            user = User.objects.get(username=user_name)  # 读取该用户信息
            if pass_word == user.password:  # 检查密码是否匹配
                request.session['IS_LOGIN'] = True
                request.session['nickname'] = user.nickname
                request.session['username'] = user_name
                return render(request, 'index.html', {'user': user})
            else:
                return render(request, 'login.html', {'error': '密码错误!'})
        else:
            return render(request, 'login.html', {'error': '用户名不存在!'})


# 注册
class RegisterView(View):
    def get(self, request):
        return render(request, 'register.html')

    def post(self, request):
        user_name = request.POST.get('username', '')
        pass_word_1 = request.POST.get('password_1', '')
        pass_word_2 = request.POST.get('password_2', '')
        nick_name = request.POST.get('nickname', '')
        email = request.POST.get('email', '')
        avatar = request.FILES.get('avatar')
        if User.objects.filter(username=user_name):
            return render(request, 'register.html', {'error': '用户已存在'})
            # 将表单写入数据库
        if (pass_word_1 != pass_word_2):
            return render(request, 'register.html', {'error': '两次密码请输入一致'})
        user = User()
        user.username = user_name
        user.password = pass_word_1
        user.email = email
        user.nickname = nick_name
        user.save()
        # 返回注册成功页面
        return render(request, 'login.html')


# 详情页
class LoginsuccessView(View):
    def post(self, request):
        return render(request, 'details.html')


class Det_indexView(View):
    def get(self, request):
        return render(request, 'det_index.html')


# 文章
class WhisperView(View):
    def get(self, request):
        username = request.GET.get('username')
        global username
        # user = User.objects.filter(username=username).first()
        # username = user.username
        articleComment = ArticleComment.objects.filter(username=username).all().order_by('-id')
        if articleComment:
            body = articleComment[0].body
            time = articleComment[0].createtime

            context = {
                'username': username,
                'body': body,
                'time': time,

            }
        else:
            context = {
                'username': '',
                'body0': '',
                'body1': '',
                'time0': '',
                'time1': ''}

        return render(request, 'whisper.html', context=context)

    def post(self, request):
        body = request.POST.get('body', '')
        ArticleComment.objects.create(username=username, body=body)
        articleComment = ArticleComment.objects.filter(username=username).all().order_by('-id')
        if articleComment:
            body = articleComment[0].body

            time = articleComment[0].createtime

            context = {
                'username': username,
                'body': body,
                'time': time,
            }
        else:
            context = {
                'username': '',
                'body': '',
                'time': '',
               }

        return render(request, 'whisper.html', context=context)


class LeacotsView(View):
    def get(self, request):
        return render(request, 'leacots.html')


class AlbumView(View):
    def get(self, request):
        return render(request, 'album.html')


# 关于
class AboutView(View):
    def get(self, request):
        return render(request, 'about.html')

my_blog/my_blog/apps/index/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View

#首页
class IndexView(View):
    def get(self, request):
        return render(request, 'index.html')

my_blog/my_blog/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link href="../static/res/img/html_head.png" rel="SHORTCUT ICON">
  <title>秃顶程序员的博客</title>
  <link rel="stylesheet" type="text/css" href="../static/res/layui/css/layui.css">
  <link rel="stylesheet" type="text/css" href="../static/res/css/main.css">
<!--加载meta IE兼容文件-->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->
</head>
<body>
  <div class="header">
    <div class="menu-btn">
      <div class="menu"></div>
    </div>
    <h1 class="logo">
      <a href="http://127.0.0.1:8000/det_index/" >
        <span>MYBLOG</span>
        <img src="../static/res/img/logo.png">
      </a>
    </h1>
    <div class="nav">
      <a href="http://127.0.0.1:8000/det_index/" >注销</a>
      <a href="http://127.0.0.1:8000/whisper/">文章</a>
      <a href="http://127.0.0.1:8000/leacots/">留言</a>
      <a href="http://127.0.0.1:8000/album/">相册</a>
      <a href="http://127.0.0.1:8000/about/"  class="active">关于</a>
    </div>
    <ul class="layui-nav header-down-nav">
      <li class="layui-nav-item"><a href="http://127.0.0.1:8000/det_index/" class="active">注销</a></li>
      <li class="layui-nav-item"><a href="http://127.0.0.1:8000/whisper/">文章</a></li>
      <li class="layui-nav-item"><a href="http://127.0.0.1:8000/leacots/">留言</a></li>
      <li class="layui-nav-item"><a href="http://127.0.0.1:8000/album/">相册</a></li>
      <li class="layui-nav-item"><a href="http://127.0.0.1:8000/about/"  class="active">关于</a></li>
    </ul>
    <p class="welcome-text">
      欢迎来到<span class="name">个人</span>博客系统~
    </p>
  </div>

  <div class="about-content">
    <div class="w1000">
      <div class="item info">
        <div class="title">
          <h3>我的介绍</h3>
        </div>
        <div class="cont">
          <img src="../static/res/img/xc_img1.jpg">
          <div class="per-info">
            <p>
              <span class="name">范腾飞</span><br />
              <span class="age">23岁</span><br />
              <span class="Career">python开发工程师</span><br />
              <span class="interest">爱好交友，写作，敲代码</span>
            </p>
          </div>
        </div>
      </div>
      <div class="item tool">
        <div class="title">
          <h3>我的技能</h3>
        </div>
        <div class="layui-fluid">
          <div class="layui-row">
            <div class="layui-col-xs6 layui-col-sm3 layui-col-md3">
              <div class="cont-box">
                <img src="../static/res/img/gr_img2.jpg">
                <p>80%</p>
              </div>
            </div>
            <div class="layui-col-xs6 layui-col-sm3 layui-col-md3">
              <div class="cont-box">
                <img src="../static/res/img/gr_img3.jpg">
                <p>80%</p>
              </div>
            </div>
            <div class="layui-col-xs6 layui-col-sm3 layui-col-md3">
              <div class="cont-box">
                <img src="../static/res/img/gr_img4.jpg">
                <p>80%</p>
              </div>
            </div>
            <div class="layui-col-xs6 layui-col-sm3 layui-col-md3">
              <div class="cont-box">
                <img src="../static/res/img/gr_img5.jpg">
                <p>80%</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  

  <div class="footer-wrap">
      <div class="footer w1000">
      <div class="qrcode">
        <img width="160px" src="../static/res/img/wx.jpg">
      </div>
      <div class="practice-mode">
        <!-- <img src="res/img/down_img.jpg"> -->
        <div class="text">
          <h4 class="title">我的联系方式</h4>
		  <p>手机<span class="iphone">18727304847</span></p>
		  <p>Q&nbsp;Q<span class="email">1054708847</span></p>
		  <p>邮箱<span class="email">1054708847@qq.com</span></p>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript" src="../static/res/layui/layui.js"></script>
  <script type="text/javascript">
    layui.config({
      base: 'res/js/util/'
    }).use(['element','laypage','form','layer','menu'],function(){
      element = layui.element,laypage = layui.laypage,form = layui.form,layer = layui.layer,menu = layui.menu;
      menu.init();
    })
  </script>
</body>
</html>

my_blog/my_blog/templates/index.html
{% load static %}
<html lang="zh">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="TNT">

    <!-- CSS -->
	<title>Ericam_blog</title>
	<link rel="shortcut icon" href="{% static 'css/images/gt_favicon.png' %}">
	<link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-theme.css'%}"  >
	<link rel="stylesheet" href="{% static 'css/log.css'%}">
	<link rel="stylesheet" href="{% static 'css/blog.css'%}">
	</head>


<body class="back">
  <!--导航栏-->
	<div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				<a class="navbar-brand"><img src="{%static 'css/images/lo.png'%}" alt="Progressus HTML5 template"></a>
			</div>
			<div class="nav navbar-nav navbar-right">
				<a class="btn" href="{% url 'blogs:login'%}">登录 / 注册</a></li>
			</div>
		</div>
	</div>

	  <center>
    <div class="container" style="padding-top:300px;min-height:800px">
      <div class="row">,.
        <p class="lead"><font color="white">个人博客系统，尽情的享用吧(〃'▽'〃)</font></p>
        <p class="tagline"><font color="white">欢迎面试官给出建议</font></p>
		  <p><a class="btn btn-action btn-lg" role="button" href="{% url 'blogs:login'%}">START NOW</a></p>
      </div>
    </div>
	</center>


   <footer id="footer" class="top-space">
		<div class="footer2">
			<div class="container">
				<p class="text-center">Copyright &copy; 2020, Ericam_blog</p>
			</div>
		</div>
  </footer>
</body>
</html>

my_blog/my_blog/templates/login.html
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link rel="shortcut icon" href="{% static 'css/images/gt_favicon.png' %}">
    <link rel="stylesheet" href="{%static 'css/log.css' %}">
    <link rel="stylesheet" href="{%static 'css/semantic.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
</head>
<body class="login">
    <div class="ui center aligned grid" style="margin-top: 200px">
        <div class="ui six wide column">
            <h1 class="ui teal header">Ericam blog-登录</h1>
            <div class="ui segment">
                <div class="ui content">
    <form class="ui large form" method="get" action="{% url 'blogs:whisper'%}">
      <div class="ui stacked segment">
        <div class="field">
          <div class="ui left icon input">
            <input type="text" name="username" placeholder="请输入用户名">
          </div>
        </div>
        <div class="field">
          <div class="ui left icon input">
            <input type="password" name="password" placeholder="请输入密码">
          </div>
        </div>
        {{ error }}<br>
        <button class="ui fluid large teal button" type="submit">登陆</button>
      </div>
      <div class="ui error message"></div>
    </form>

    <div class="ui message">
       <a href="http://127.0.0.1:8000/register/">注册</a>
    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

my_blog/my_blog/templates/register.html
{%load static%}
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="shortcut icon" href="{% static 'css/images/gt_favicon.png' %}">
    <link rel="stylesheet" href="{%static 'css/log.css' %}">
    <link rel="stylesheet" href="{%static 'css/semantic.css' %}">
</head>
<body class="register">
    <div class="ui center aligned grid" style="margin-top: 200px">
        <div class="ui six wide column">
            <h1 class="ui teal header"><font color="black">EricamBlog-用户注册</font></h1>
            <div class="ui segment">
                <div class="ui content">
                    <form class="ui form" method="post" action="{%url 'blogs:register'%}"  enctype="multipart/form-data">
                        <div class="field">
                            <input type="text" name="username" placeholder="请输入用户名"><br>
                        </div>
                        <div class="field">
                            <input type="password" name="password_1" placeholder="请输入密码"><br>
                        </div>
                        <div class="field">
                            <input type="password" name="password_2" placeholder="请确认密码"><br>
                        </div>
                        <div class="field">
                            <input type="text" name="nickname" placeholder="请输入昵称"><br>
                        </div>

                        <button class="ui fluid large teal button" type="submit">注册</button>

                    </form>

                </div>
            </div>
        </div>
    </div>
</body>
</html>

my_blog/my_blog/templates/whisper.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link href="../static/res/img/html_head.png" rel="SHORTCUT ICON">
  <title>秃顶程序员的博客</title>
  <link rel="stylesheet" type="text/css" href="../static/res/layui/css/layui.css">
  <link rel="stylesheet" type="text/css" href="../static/res/css/main.css">
<!--加载meta IE兼容文件-->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->
</head>
<body>
  <div class="header">
    <div class="menu-btn">
      <div class="menu"></div>
    </div>
    <h1 class="logo">
      <a href="http://127.0.0.1:8000/det_index/" >
        <span>MYBLOG</span>
        <img src="../static/res/img/logo.png">
      </a>
    </h1>
    <div class="nav">
      <a href="http://127.0.0.1:8000/det_index/" >注销</a>
      <a href="http://127.0.0.1:8000/whisper/">文章</a>
      <a href="http://127.0.0.1:8000/leacots/">留言</a>
      <a href="http://127.0.0.1:8000/album/">相册</a>
      <a href="http://127.0.0.1:8000/about/"  class="active">关于</a>
    </div>
    <ul class="layui-nav header-down-nav">
      <li class="layui-nav-item"><a href="http://127.0.0.1:8000/det_index/" class="active">注销</a></li>
      <li class="layui-nav-item"><a href="http://127.0.0.1:8000/whisper/">文章</a></li>
      <li class="layui-nav-item"><a href="http://127.0.0.1:8000/leacots/">留言</a></li>
      <li class="layui-nav-item"><a href="http://127.0.0.1:8000/album/">相册</a></li>
      <li class="layui-nav-item"><a href="http://127.0.0.1:8000/about/"  class="active">关于</a></li>
    </ul>
    <p class="welcome-text">
      欢迎来到<span class="name">个人</span>博客系统~
    </p>
  </div>


  <div class="content whisper-content">
    <div class="cont">
      <div class="whisper-list">
        <div class="item-box">
          <div class="item">
            <div class="whisper-title">
              <i class="layui-icon layui-icon-date"></i><span class="hour">12:25</span><span class="date">2018/06/08</span>
            </div>
            <p class="text-cont">
              一直听说牛油果吃起来像肥皂、肥肉，虽然很难吃，但是价格却很贵，我还是想尝试一下。今天公司新到了新西兰牛油果，这是新西兰牛油果是第一次在中国上市，个头比普通牛油果大了一倍，被誉为“超牛果”。好奇心驱使我尝了一颗，第一次吃牛油果没有见识，切开牛油果费了好大劲，切成了这样。
            </p>
            <div class="img-box">
              <img src="../static/res/img/wy_img1.jpg">
            </div>
            <div class="op-list">
              <p class="like"><i class="layui-icon layui-icon-praise"></i><span>1200</span></p>
              <p class="off"><span>评论</span><i class="layui-icon layui-icon-down"></i></p>
            </div>
          </div>
          <div class="review-version layui-hide">
              <div class="form">
                <img src="../static/res/img/header2.png">
                    <form class="ui large form" method="post" action="{% url 'blogs:whisper'%}">
                      <div class="ui stacked segment">
                        <div class="field">
                          <div class="ui left icon input">
                            <input type="text" name="body" placeholder="期待您的评论">
                          </div>
                        </div>
                        </div>
                        <button class="ui fluid large teal button" type="submit">评论</button>
                      <div class="ui error message"></div>
                     </form>
                <!--<form class="layui-form" method="post" action="{% url 'blogs:whisper' %}">-->
                  <!--<div class="layui-form-item layui-form-text">-->
                    <!--<div class="layui-input-block">-->
                      <!--<textarea name="desc" class="layui-textarea"></textarea>-->
                    <!--</div>-->
                  <!--</div>-->
                  <!--<div class="layui-form-item">-->
                    <!--<div class="layui-input-block" style="text-align: right;">-->
                      <!--<button class="layui-btn definite" type="submit">確定</button>-->
                    <!--</div>-->
                  <!--</div>-->
                <!--</form>-->
              </div>
              <div class="list-cont">
                <div class="cont">
                  <div class="img">
                    <img src="../static/res/img/header.png" alt="">
                  </div>
                  <div class="text">
                    <p class="tit"><span class="name">{{ username }}</span><span class="data">{{ time }}</span></p>
                    <p class="ct">{{ body }}</p>
                  </div>
                </div>
              </div>
          </div>
        </div>
        <div class="item-box">
          <div class="item">
            <div class="whisper-title">
              <i class="layui-icon layui-icon-date"></i><span class="hour">12:25</span><span class="date">2018/06/08</span>
            </div>
            <p class="text-cont">
              一直听说牛油果吃起来像肥皂、肥肉，虽然很难吃，但是价格却很贵，我还是想尝试一下。今天公司新到了新西兰牛油果，这是新西兰牛油果是第一次在中国上市，个头比普通牛油果大了一倍，被誉为“超牛果”。好奇心驱使我尝了一颗，第一次吃牛油果没有见识，切开牛油果费了好大劲，切成了这样。
            </p>
            <div class="img-box">
              <img src="../static/res/img/wy_img2.jpg">
              <img src="../static/res/img/wy_img3.jpg">
              <img src="../static/res/img/wy_img4.jpg">
            </div>
            <div class="op-list">
              <p class="like"><i class="layui-icon layui-icon-praise"></i><span>0</span></p>
              <p class="edit"><i class="layui-icon layui-icon-reply-fill"></i><span>1200</span></p>
              <p class="off"><span>展开</span><i class="layui-icon layui-icon-down"></i></p>
            </div>
          </div>
          <div class="review-version layui-hide">
              <div class="form">
                <img src="../static/res/img/header2.png">
                  <form class="ui large form" method="post" action="{% url 'blogs:whisper'%}">
                      <div class="ui stacked segment">
                        <div class="field">
                          <div class="ui left icon input">
                            <input type="text" name="body" placeholder="期待您的评论">
                          </div>
                        </div>
                        </div>
                        <button class="ui fluid large teal button" type="submit">评论</button>
                      <div class="ui error message"></div>
                     </form>
              </div>
              <div class="list-cont">
                <div class="cont">
                  <div class="img">
                    <img src="../static/res/img/header.png" alt="">
                  </div>
                  <div class="text">
                    <p class="tit"><span class="name">{{ username }}</span><span class="data">{{ time }}</span></p>
                    <p class="ct">{{ body }}</p>
                  </div>
                </div>

                <div class="cont">
                  <div class="img">
                    <img src="../static/res/img/header.png" alt="">
                  </div>
                </div>
              </div>
          </div>
        </div>
        <div class="item-box">
          <div class="item">
            <div class="whisper-title">
              <i class="layui-icon layui-icon-date"></i><span class="hour">12:25</span><span class="date">2018/06/08</span>
            </div>
            <p class="text-cont">
              一直听说牛油果吃起来像肥皂、肥肉，虽然很难吃，但是价格却很贵，我还是想尝试一下。今天公司新到了新西兰牛油果，这是新西兰牛油果是第一次在中国上市，个头比普通牛油果大了一倍，被誉为“超牛果”。好奇心驱使我尝了一颗，第一次吃牛油果没有见识，切开牛油果费了好大劲，切成了这样。
            </p>
            <div class="img-box">
              <img src="../static/res/img/wy_img5.jpg">
            </div>
            <div class="op-list">
              <p class="like"><i class="layui-icon layui-icon-praise"></i><span>1200</span></p>
              <p class="edit"><i class="layui-icon layui-icon-reply-fill"></i><span>1200</span></p>
              <p class="off" off = 'true'><span>收起</span><i class="layui-icon layui-icon-up"></i></p>
            </div>
          </div>
          <div class="review-version">
              <div class="form">
                <img src="../static/res/img/header2.png">
                  <form class="ui large form" method="post" action="{% url 'blogs:whisper'%}">
                      <div class="ui stacked segment">
                        <div class="field">
                          <div class="ui left icon input">
                            <input type="text" name="body" placeholder="期待您的评论">
                          </div>
                        </div>
                        </div>
                        <button class="ui fluid large teal button" type="submit">评论</button>
                      <div class="ui error message"></div>
                     </form>
              </div>
              <div class="list-cont">
                <div class="cont">
                  <div class="img">
                    <img src="../static/res/img/header.png" alt="">
                  </div>
                  <div class="text">
                    <p class="tit"><span class="name">{{ username }}</span><span class="data">{{ time }}</span></p>
                    <p class="ct">{{ body }}</p>
                  </div>
                </div>
                <div class="cont">
                  <div class="img">
                    <img src="../static/res/img/header.png" alt="">
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>
      <div id="demo" style="text-align: center;"></div>
    </div>
  </div>
  <!--<script type="text/html" id="laytplCont">-->
    <!--<div class="cont">-->
      <!--<div class="img">-->
        <!--<img src="../static/res/img/header2.png" alt="">-->
      <!--</div>-->
      <!--<div class="text">-->
        <!--<p class="tit"><span class="name">{{d.name}}</span><span class="data">2018/06/06</span></p>-->
        <!--<p class="ct">{{d.cont}}</p>-->
      <!--</div>-->
    <!--</div>-->
  <!--</script>-->
  <script type="text/javascript" src="../static/res/layui/layui.js"></script>
  <script type="text/javascript">
   layui.config({
      base: '../static/res/js/util/'
    }).use(['element','laypage','form','menu'],function(){
      element = layui.element,laypage = layui.laypage,form = layui.form,menu = layui.menu;
      laypage.render({
        elem: 'demo'
        ,count: 70 //数据总数，从服务端得到
      });
      menu.init();
      menu.off();
      menu.submit()
    })
  </script>
</body>
</html>